---
# kafkaPlaybook.yml
- hosts: all
  user: vagrant
  sudo: True

  tasks:

    - name: install linux packages
      action: apt update_cache=yes pkg={{item}} state=installed
      with_items:
        - vim
        - openjdk-7-jdk
        - python-pip

    - name: make /usr/local/kafka directory
      shell: "mkdir /usr/local/kafka"

    - name: download kafka (the link is from an apache mirror)
      get_url: url=http://apache.spinellicreations.com/kafka/0.8.1.1/kafka-0.8.1.1-src.tgz dest=/usr/local/kafka/kafka-0.8.1.1-src.tgz mode=0440

    - name: untar file
      shell: "tar -xvf /usr/local/kafka/kafka-0.8.1.1-src.tgz -C /usr/local/kafka"

    - name: build kafka with gradle
      shell: "cd /usr/local/kafka/kafka-0.8.1.1-src && ./gradlew jar"

    - name: Install pip packages
      pip: name={{item}} state=present
      with_items:
        - kazoo
        - kafka-python

    - name: uncomment the advertised.host.name line
        lineinfile: dest=/usr/local/kafka/kafka-0.8.1.1-src/config/server.properties 
                    regexp='^#advertised.host.name=localhost'
                    insertafter='^#advertised.host.name=localhost'
                    line='#advertised.host.name=localhost'
                    state=present

    - name: uncomment the advertised.port line
        lineinfile: dest=/usr/local/kafka/kafka-0.8.1.1-src/config/server.properties 
                    regexp='^#advertised.port=9092'
                    insertafter='^#advertised.port=9092'
                    line='advertised.port=9092'
                    state=present

    - name: Copy zookeeper shell script
      copy: src=start-single-node-zookeeper.sh dest=/usr/local/kafka/kafka-0.8.1.1-src/start-single-node-zookeeper.sh owner=root group=root mode=755 backup=yes

    - name: Copy zookeeper upstart file
      copy: src=single-node-zookeeper.conf dest=/etc/init/single-node-zookeeper.conf owner=root group=root mode=644 backup=yes

    - name: Start zookeeper
      service: name=single-node-zookeeper state=started

    - name: Copy kafka shell script
      copy: src=start-single-node-kafka.sh dest=/usr/local/kafka/kafka-0.8.1.1-src/start-single-node-kafka.sh owner=root group=root mode=755 backup=yes

    - name: Copy kafka upstart file
      copy: src=single-node-kafka.conf dest=/etc/init/single-node-kafka.conf owner=root group=root mode=644 backup=yes

    - name: Start kafka
      service: name=single-node-kafka state=started
